Repository PositionExchange/position-protocol, pull requests merged in 2022-03, with the labels that each got.

#59 expose interface manager
  contracts/interfaces/IPositionManager.sol
  contracts/protocol/PositionManager.sol
  contracts/protocol/libraries/types/PositionManagerStorage.sol
  package.json
Labels: non logic changed

#78 Refactor/market maker
  contracts/interfaces/IPositionManager.sol
  contracts/protocol/PositionHouse.sol
  contracts/protocol/PositionManager.sol
  contracts/protocol/libraries/types/MarketMaker.sol
  contracts/protocol/modules/MarketMaker.sol
  test/shared/deploy.ts
  test/shared/utilities.ts
  test/unit/MarketMaker.spec.ts
  test/unit/PositionHouse_01.spec.ts
  test/unit/PositionHouse_02.spec.ts
Labels: enhancement

#74 add function change leverage for position manager
  contracts/interfaces/IPositionManager.sol
  contracts/protocol/PositionHouse.sol
  contracts/protocol/PositionManager.sol
  contracts/protocol/libraries/types/PositionManagerStorage.sol
  contracts/protocol/modules/LimitOrder.sol
Labels: enhancement, logic changed

#77 update partially fill
  contracts/protocol/libraries/position/LimitOrder.sol
  contracts/protocol/libraries/position/TickPosition.sol
  test/unit/PositionHouse_02.spec.ts
Labels: logic changed

#84 Fix scanning aler: missing events arithmeti
  contracts/protocol/PositionHouse.sol
Labels: issue

#85 Scanning Alert: using safe transfer
  contracts/protocol/InsuranceFund.sol
Labels: issue

#86 missing events arithmetic
  contracts/protocol/PositionHouse.sol
  contracts/protocol/modules/CumulativePremiumFractions.sol
Labels: issue

#68 add require same side when open limit and market
  contracts/protocol/PositionHouse.sol
  contracts/protocol/libraries/helpers/Errors.sol
  contracts/protocol/modules/LimitOrder.sol
  test/shared/positionHouseTestingTool.ts
  test/unit/FundingRate.spec.ts
  test/unit/PositionHouse_01.spec.ts
  test/unit/PositionHouse_02.spec.ts
Labels: logic changed

#69 improve insurancefund
  contracts/protocol/InsuranceFund.sol
Labels: enhancement, logic changed

#97 Musketdev/using safe erc20 upgrade
  .gitignore
  .openzeppelin/unknown-97.json
  contracts/protocol/InsuranceFund.sol
Labels: bug
